"""Refresh the live counts in handover.md (T.3).

Hand-typed numbers rot: this week's "780 passing" became 840, then 848, and the
document still claimed the old figure in two places. So the counts are now
*generated* between two markers in ``handover.md`` --

    <!-- refresh_docs:begin -->
    ...generated table...
    <!-- refresh_docs:end -->

-- and ``tests/test_docs_freshness.py`` fails when the block drifts from the
repository, and when a hand-typed count reappears in the live part of the
document (dated history sections are exempt; they are a log, not a claim).

Usage:
    python tools/refresh_docs.py            # rewrite the block in handover.md
    python tools/refresh_docs.py --check    # exit 1 when it is stale (CI gate)
    python tools/refresh_docs.py --print    # print the block without writing
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from collections import OrderedDict
from pathlib import Path
from typing import Dict, List, Optional

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from game.data.registry import GameDataRegistry  # noqa: E402
from game.validation.data_validator import validate_all_game_data  # noqa: E402
from game.validation.dead_content import build_report  # noqa: E402

HANDOVER = PROJECT_ROOT / "handover.md"
LOCATION_ART = PROJECT_ROOT / "frontend-godot" / "assets" / "locations"

BEGIN_MARKER = "<!-- refresh_docs:begin -->"
END_MARKER = "<!-- refresh_docs:end -->"

#: ``887 tests collected in 0.47s`` -- pytest's own --collect-only summary.
_COLLECTED = re.compile(r"(\d+)\s+tests?\s+collected")

#: A hand-typed count in prose. Two digits or more so "3 skipped" in a table of
#: results does not trip it, but "780 passed" and "840 tests" do.
_HAND_TYPED = re.compile(r"\b\d{2,}\s+(?:tests?|passed|passing|skipped|errors?)\b", re.IGNORECASE)

#: A heading that dates itself is history: the numbers under it are a log entry.
_DATED_HEADING = re.compile(r"\d{4}-\d{2}-\d{2}")


def count_tests() -> int:
    """How many tests the suite collects (no execution, so it is cheap)."""
    result = subprocess.run(
        [sys.executable, "-m", "pytest", "--collect-only", "-q"],
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True,
        timeout=300,
    )
    match = _COLLECTED.search(result.stdout or "")
    if not match:
        raise RuntimeError(f"could not read the collected test count:\n{result.stdout[-2000:]}")
    return int(match.group(1))


def compute_counts() -> "OrderedDict[str, str]":
    """Every live count the document claims, read from the repository itself."""
    registry = GameDataRegistry.load()
    dead = build_report(registry)
    unreachable = sum(len(ids) for ids in dead["unreachable"].values())
    traps = sum(len(entries) for entries in dead["traps"].values())
    catalogue = dead["counts"]

    art = sorted(LOCATION_ART.glob("*.png"))
    location_ids = {str(entry.get("id", "")) for entry in registry.locations}
    locations_with_art = sum(1 for path in art if path.stem in location_ids)

    return OrderedDict(
        [
            ("Tests collected (`pytest --collect-only -q`)", f"{count_tests()}"),
            ("Validator errors (`validate_all_game_data`)", f"{len(validate_all_game_data().errors)}"),
            ("Dead-content sweep", f"{unreachable} unreachable, {traps} trap options"),
            ("Locations", f"{len(location_ids)} ({locations_with_art} with artwork)"),
            ("Skills", f"{catalogue['skills']}"),
            ("Items / equipment", f"{catalogue['items']} / {catalogue['equipment']}"),
            ("Enemies (named foes)", f"{catalogue['enemies']} ({catalogue['named_foes']})"),
            ("Characters", f"{catalogue['characters']}"),
            ("Sects", f"{len(registry.sects)}"),
            ("Quests", f"{catalogue['quests']}"),
            ("Secret realms", f"{catalogue['secret_realms']}"),
            ("Recipes", f"{catalogue['recipes']}"),
            ("Daos / origins", f"{catalogue['daos']} / {catalogue['origins']}"),
        ]
    )


def render_block(counts: "OrderedDict[str, str]") -> str:
    """The generated markdown block, markers included."""
    lines = [
        BEGIN_MARKER,
        "<!-- Generated by `python tools/refresh_docs.py`; a test fails when this drifts. -->",
        "",
        "| Live count | Value |",
        "|---|---|",
    ]
    lines += [f"| {label} | {value} |" for label, value in counts.items()]
    lines.append(END_MARKER)
    return "\n".join(lines)


def current_block(text: str) -> str:
    """The block as it stands in the document (markers included)."""
    start = text.find(BEGIN_MARKER)
    end = text.find(END_MARKER)
    if start == -1 or end == -1:
        raise RuntimeError(f"{HANDOVER.name} is missing the refresh_docs markers")
    return text[start : end + len(END_MARKER)]


def apply_block(text: str, block: str) -> str:
    """Replace the generated block in ``text``."""
    start = text.find(BEGIN_MARKER)
    end = text.find(END_MARKER)
    if start == -1 or end == -1:
        raise RuntimeError(f"{HANDOVER.name} is missing the refresh_docs markers")
    return text[:start] + block + text[end + len(END_MARKER) :]


def hand_typed_counts(text: str) -> List[str]:
    """Hand-typed live counts, as one string per offending line.

    Skipped: the generated block itself, and everything inside a dated section.
    A dated heading (``## 3. Recent work (2026-08-14, ...)``) makes its whole
    subtree history -- including its undated sub-headings -- because "605 passed"
    was true in August and stays true. Everything else in the document is a claim
    about the repository as it is now, and must be generated.
    """
    offenders: List[str] = []
    in_block = False
    dated = False
    #: (heading level, is dated) for the sections currently open.
    stack: List[tuple] = []
    for line in text.splitlines():
        if BEGIN_MARKER in line:
            in_block = True
            continue
        if END_MARKER in line:
            in_block = False
            continue
        if in_block:
            continue
        stripped = line.lstrip()
        if stripped.startswith("#"):
            level = len(stripped) - len(stripped.lstrip("#"))
            while stack and stack[-1][0] >= level:
                stack.pop()
            inherited = stack[-1][1] if stack else False
            stack.append((level, inherited or bool(_DATED_HEADING.search(line))))
            dated = stack[-1][1]
            continue
        if dated:
            continue
        if _HAND_TYPED.search(line):
            offenders.append(line.strip())
    return offenders


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Refresh the live counts in handover.md (T.3).")
    parser.add_argument("--check", action="store_true", help="exit 1 when the block is stale")
    parser.add_argument("--print", dest="print_only", action="store_true", help="print the block and stop")
    arguments = parser.parse_args(argv)

    counts = compute_counts()
    block = render_block(counts)
    text = HANDOVER.read_text(encoding="utf-8")

    if arguments.print_only:
        print(block)
        return 0

    if arguments.check:
        problems = []
        if current_block(text) != block:
            problems.append("the generated count block is stale")
        offenders = hand_typed_counts(text)
        if offenders:
            problems.append("hand-typed counts: " + "; ".join(offenders))
        if problems:
            for problem in problems:
                print(f"FAIL: {problem}", file=sys.stderr)
            print("\nRun: python tools/refresh_docs.py", file=sys.stderr)
            return 1
        print("handover.md is fresh")
        return 0

    HANDOVER.write_text(apply_block(text, block), encoding="utf-8")
    print(f"refreshed {HANDOVER.name} ({len(counts)} counts)")
    offenders = hand_typed_counts(HANDOVER.read_text(encoding="utf-8"))
    if offenders:
        print("still hand-typed (fix these):")
        for offender in offenders:
            print(f"  {offender}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
